/**
 * Amazon SNS — Fraud Alert Notifications
 * Publishes email alerts to an SNS topic when fraud is detected.
 * Email subscribers must confirm their subscription via AWS console.
 */
import { PublishCommand } from '@aws-sdk/client-sns';
import { getSNSClient } from './aws';

const TOPIC_ARN = process.env.AWS_SNS_FRAUD_TOPIC_ARN;

/**
 * Publish a fraud alert to the SNS topic.
 * @param {object} params
 * @param {string} params.userId    - User ID that triggered the alert
 * @param {string} params.userName  - Display name (for readability)
 * @param {number} params.amount    - Transaction amount in CC
 * @param {string} params.type      - Transaction type
 * @param {string} params.severity  - 'high' | 'medium' | 'low'
 * @param {string[]} params.reasons - List of fraud rule violations
 */
export async function publishFraudAlert({ userId, userName, amount, type, severity, reasons }) {
  if (!TOPIC_ARN) {
    console.warn('[SNS] AWS_SNS_FRAUD_TOPIC_ARN not set — skipping alert');
    return;
  }

  const sns = getSNSClient();

  const severityEmoji = severity === 'high' ? '🔴' : severity === 'medium' ? '🟡' : '🟢';
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const subject = `${severityEmoji} [CampusChain] Fraud Alert — ${severity.toUpperCase()} Severity`;

  const message = `
╔══════════════════════════════════════════════╗
   CAMPUSCHAIN FRAUD DETECTION ALERT
╚══════════════════════════════════════════════╝

Severity    : ${severity.toUpperCase()} ${severityEmoji}
Time (IST)  : ${timestamp}
User ID     : ${userId}
User Name   : ${userName || 'Unknown'}
Transaction : ${amount} CC (${type})

──── Triggered Rules ────────────────────────
${reasons.map((r, i) => `  ${i + 1}. ${r}`).join('\n')}
─────────────────────────────────────────────

⚠️  Please review this transaction in the admin panel:
    /admin → Fraud Alerts

This alert was automatically generated by the
CampusChain Rule-Based Fraud Detection Engine.
`.trim();

  try {
    const result = await sns.send(
      new PublishCommand({
        TopicArn: TOPIC_ARN,
        Subject: subject,
        Message: message,
        MessageAttributes: {
          severity: {
            DataType: 'String',
            StringValue: severity,
          },
          userId: {
            DataType: 'String',
            StringValue: String(userId),
          },
        },
      })
    );
    console.log('[SNS] Fraud alert published. MessageId:', result.MessageId);
    return result.MessageId;
  } catch (err) {
    console.error('[SNS] Failed to publish fraud alert:', err.message);
  }
}
